# Generated by Django 4.2 on 2025-08-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="checkout_id",
            field=models.CharField(default="", max_length=256),
            preserve_default=False,
        ),
    ]
