# Generated by Django 4.2 on 2025-08-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_payment_checkout_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("successful", "Successful"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                    ("unknown", "Unknown"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
